### ISSUE TITLE
auto_aspect_test.txt

### ISSUE THREAD

**Issue by bluesky632** [guuboi/AspectSentiment#1]
作者您好，非常感谢您开源的这份代码，我最近在学习细粒度情感分析，您的代码给了我很大的帮助，我想问一下，细粒度的情感分析数据集是不是都需要标注属性，请问您的数据集是如何标注的，人工标注的还是有辅助的工具？然后我在尝试运行这个代码的时候，发现少了一个auto_aspect_test.txt文件，请问可以提供一份给我吗？谢谢您。

**Comment by guuboi** [comment]
样本集文件名字命名错误，已经修改过来了。

**Comment by bluesky632** [comment]
谢谢您！我重新下载了这个代码，运行train.py文件时，报了一个错误，麻烦您帮忙看看
`Traceback (most recent call last):
  File "G:/AspectSentiment-master/train.py", line 67, in <module>
    train()
  File "G:/AspectSentiment-master/train.py", line 23, in train
    train = load_corpus(config.train_file, word2id, max_sen_len=config.max_sen_len)
  File "G:\AspectSentiment-master\utils.py", line 86, in load_corpus
    labels = [cat2id[l] for l in labels]
  File "G:\AspectSentiment-master\utils.py", line 86, in <listcomp>
    labels = [cat2id[l] for l in labels]
KeyError: '0'`
